services:
  - type: web
    name: motosnap-backend
    runtime: docker
    plan: free
    env: production
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: UPLOAD_DIR
        value: "/app/uploads"
      - key: JWT_SECRET
        generateValue: true
      - key: SPRING_DATASOURCE_URL
        value: "jdbc:h2:mem:motosnapdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: "org.h2.Driver"
      - key: SPRING_JPA_DATABASE_PLATFORM
        value: "org.hibernate.dialect.H2Dialect"
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: "create-drop"
      - key: JAVA_OPTS
        value: "-Xmx400m -Xms200m"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://*.vercel.app,http://localhost:3000,https://motosnap-client-2z8cappxr-vssmotos-projects.vercel.app"
      - key: CORS_ALLOWED_METHODS
        value: "GET,POST,PUT,DELETE,OPTIONS"
      - key: CORS_ALLOWED_HEADERS
        value: "Authorization,Content-Type,X-Requested-With,Accept,Origin,Cache-Control,Pragma,Expires,If-Modified-Since,User-Agent"
    healthCheckPath: /actuator/health