# Test Environment Configuration
spring:
  datasource:
    # Use H2 in-memory database for tests
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 2  # Minimal pool for tests
      minimum-idle: 1
  
  jpa:
    hibernate:
      ddl-auto: create-drop  # Fresh schema for each test
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false
  
  h2:
    console:
      enabled: true
      path: /h2-console

# JWT Configuration - Simple for tests
jwt:
  secret: "test-secret-key-32-characters-long-for-testing-purposes-only"
  expiration:
    access: 300000     # 5 minutes for faster test cycles
    refresh: 1800000   # 30 minutes

# Logging - Minimal for tests
logging:
  level:
    com.motosnap.workshop: WARN
    org.springframework.security: WARN
    org.hibernate: WARN
    org.springframework.test: INFO